spring.application.name=QuizPage
spring.datasource.url=jdbc:postgresql://localhost:5432/Testing
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
